version: '2'
services:
    geodocker-pbase:
        build:
          context: ./base
          # choose one of images (centos.dockerfile / ubuntu.dockerfile)
          dockerfile: centos.dockerfile
        image: geodocker-pbase:latest
    geodocker-zookeeper:
        build: ./zookeeper
        image: daunnc/geodocker-zookeeper:latest
        depends_on:
          - geodocker-pbase
    geodocker-hadoop:
        build: ./hadoop
        image: daunnc/geodocker-hadoop:latest
        depends_on:
          - geodocker-zookeeper
    geodocker-accumulo:
        build: ./accumulo
        image: daunnc/geodocker-accumulo:latest
        depends_on:
          - geodocker-hadoop
    geodocker-accumulo-geowave:
        build:
          context: ./accumulo
          args:
            WITH_GEOWAVE: "true"
        image: daunnc/geodocker-accumulo:latest
        depends_on:
          - geodocker-accumulo
    geodocker-accumulo-geomesa:
        build:
          context: ./accumulo
          args:
            WITH_GEOMESA: "true"
        image: daunnc/geodocker-accumulo:latest
        depends_on:
          - geodocker-accumulo
    geodocker-accumulo-wavemesa-combined:
        build:
          context: ./accumulo
          args:
            WITH_GEOMESA: "true"
            WITH_GEOWAVE: "true"
        image: daunnc/geodocker-accumulo:latest
        depends_on:
          - geodocker-accumulo
    geodocker-spark:
        build: ./spark
        image: daunnc/geodocker-spark:latest
        depends_on:
          - geodocker-hadoop
    #geodocker-geoserver:
    #    build: ./extras/geoserver
    #    image: daunnc/geodocker-geoserver:latest
    #    depends_on:
    #      - geodocker-spark
