version: '2'
services:    
    geodocker-zookeeper:
        image: daunnc/geodocker-zookeeper:latest
        # volumes:
        #   - '/data/gt/hdfs:/data/hdfs'
    geodocker-hadoop-name:
        image: daunnc/geodocker-hadoop-name:latest        
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        # volumes:
        #   - '/data/gt/hdfs:/data/hdfs'
        depends_on: 
          - geodocker-zookeeper        
    geodocker-hadoop-sname:
        image: daunnc/geodocker-hadoop-sname:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: hdfs secondarynamenode
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        # volumes:
        #  - '/data/gt/hdfs:/data/hdfs'
        depends_on:           
          - geodocker-hadoop-name
    geodocker-hadoop-data:
        image: daunnc/geodocker-hadoop-data:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: hdfs datanode
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        # volumes:
        #  - '/data/gt/hdfs:/data/hdfs'
        depends_on:
          - geodocker-hadoop-name
    geodocker-accumulo-master:
        image: daunnc/geodocker-accumulo-master:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: accumulo master
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on: 
          - geodocker-hadoop-data
    geodocker-accumulo-gc:
        image: daunnc/geodocker-accumulo-gc:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: accumulo gc
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on: 
          - geodocker-accumulo-master
    geodocker-accumulo-monitor:
        image: daunnc/geodocker-accumulo-monitor:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: accumulo monitor
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on: 
          - geodocker-accumulo-master
    geodocker-accumulo-tracer:
        image: daunnc/geodocker-accumulo-tracer:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: accumulo tracer
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on: 
          - geodocker-accumulo-master
    geodocker-accumulo-tserver:
        image: daunnc/geodocker-accumulo-tserver:latest
        entrypoint: /sbin/entrypoint-dev.sh
        command: accumulo tserver
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on: 
          - geodocker-accumulo-master
          - geodocker-accumulo-gc
          - geodocker-accumulo-monitor
          - geodocker-accumulo-tracer
    geodocker-spark-master:
        image: daunnc/geodocker-spark-master:latest        
        environment:
          SPARK_DAEMON_MEMORY: 2g
          SPARK_SUBMIT_DRIVER_MEMORY: 1g
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        # volumes:
        #  - '/data/gt/spark:/data/spark'
        depends_on: 
          - geodocker-hadoop-data
    geodocker-spark-worker:
        image: daunnc/geodocker-spark-worker:latest        
        environment: 
          SPARK_DAEMON_MEMORY: 2g
          SPARK_SUBMIT_DRIVER_MEMORY: 1g
          SPARK_WORKER_CORES: 8
          SPARK_WORKER_MEMORY: 16g
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          SPARK_MASTER: geodocker-spark-master
        depends_on: 
          - geodocker-spark-master
